name: Compile and Run efb.h tests
on: [push, pull_request]

jobs:
  ubuntu:
    strategy:
      matrix:
        cc: [gcc, clang]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Dependencies
        run: sudo apt update && sudo apt install -y ${{ matrix.cc }}
      - name: Compile efb tests
        run: ${{ matrix.cc }} -O2 -std=c89 -pedantic -Wall -Wextra -Werror -Wvla -Wconversion -Wdouble-promotion -Wsign-conversion -Wuninitialized -Winit-self -Wunused -Wunused-macros -Wunused-local-typedefs -o efb_test_${{ matrix.cc }} tests/efb_test.c
      - name: Run efb tests
        run: ./efb_test_${{ matrix.cc }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-latest-${{ matrix.cc }}-efb_test
          path: efb_test_${{ matrix.cc }}
  windows:
    strategy:
      matrix:
        cc: [gcc, clang]
        os: [windows-latest, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Compile efb tests
        run: ${{ matrix.cc }} -O2 -std=c89 -pedantic -Wall -Wextra -Werror -Wvla -Wconversion -Wdouble-promotion -Wsign-conversion -Wuninitialized -Winit-self -Wunused -Wunused-macros -Wunused-local-typedefs -o efb_test_${{ matrix.cc }}.exe tests/efb_test.c
      - name: Run efb tests
        run: .\efb_test_${{ matrix.cc }}.exe
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.os }}-${{ matrix.cc }}-efb_test
          path: efb_test_${{ matrix.cc }}.exe
